import {useEffect,useRef,useState} from 'react';
import source from '../proposals.config.json';
import {validateProposals,calculateProposal,defaultChoices,proposalItinerary} from './proposals.mjs';
import './proposals.css';
const catalog=validateProposals(source);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Number.isInteger(n)?0:2}).format(n);
const styles={'hard-soft':'Hard costs + personal allowance',shared:'Shared base + travel',winner:'Trip cost + winner scenario','split-house':'Two houses + comparison','group-package':'Choose your group package'};
const locationChoice=()=>new URL(location.href).searchParams.get('proposal')||'';
function readChoices(p){
 const out=defaultChoices(p),params=new URL(location.href).searchParams;
 for(const [key,value] of Object.entries(out))if(params.has('p_'+key)){
  const raw=params.get('p_'+key);out[key]=typeof value==='boolean'?(raw==='true'?true:raw==='false'?false:raw):typeof value==='number'?(raw.trim()===''?'':Number(raw)):raw;
 }return out;
}
function writeChoices(p,choices){
 const url=new URL(location.href);for(const key of [...url.searchParams.keys()])if(key.startsWith('p_'))url.searchParams.delete(key);
 url.searchParams.set('proposal',p.id);for(const [key,value] of Object.entries(choices))url.searchParams.set('p_'+key,String(value));
 url.hash='proposals';history.replaceState(null,'',url);
}
function Gallery({images}){
 const [selected,setSelected]=useState(0),dialog=useRef(null);
 return <><div className="proposal-gallery">{images.map((img,i)=><button className="proposal-image-button" key={img.src+i} onClick={()=>{setSelected(i);dialog.current.showModal();}} aria-label={'Enlarge: '+img.caption}><img src={img.src} alt={img.caption} loading="lazy"/><span>{img.caption}</span></button>)}</div><dialog className="proposal-dialog" ref={dialog}><button className="btn btn2" onClick={()=>dialog.current.close()}>Close image</button><img src={images[selected].src} alt={images[selected].caption}/><p>{images[selected].caption}</p><div className="button-row"><button className="btn btn2" onClick={()=>setSelected((selected+images.length-1)%images.length)}>Previous image</button><button className="btn btn2" onClick={()=>setSelected((selected+1)%images.length)}>Next image</button></div></dialog></>;
}
function RouteMap({p}){
 const [selected,setSelected]=useState(p.courses[0].id),[zoom,setZoom]=useState(1),course=p.courses.find(c=>c.id===selected)||p.courses[0];
 return <section className="card"><h3>An outline of the weekend</h3><p>This diagram shows the idea. It is not a road map or driving guidance.</p><div className="button-row"><button className="btn btn2" onClick={()=>setZoom(Math.min(2,zoom+.25))} disabled={zoom>=2}>Zoom in</button><button className="btn btn2" onClick={()=>setZoom(Math.max(1,zoom-.25))} disabled={zoom<=1}>Zoom out</button><button className="btn btn2" onClick={()=>setZoom(1)}>Reset map</button></div><div className="proposal-map-scroll" tabIndex="0" aria-label="Scrollable outline map"><svg viewBox="0 0 800 500" style={{width:100*zoom+'%'}} role="group" aria-label="Choose a course on the outline map"><rect width="800" height="500" fill="var(--forest-pale)" rx="12"/><path d={'M 400 380 '+p.courses.map(c=>`L ${c.x} ${c.y}`).join(' ')} fill="none" stroke="var(--gold-dk)" strokeWidth="3" strokeDasharray="8 8"/><text x="400" y="417" textAnchor="middle">Shared base</text><circle cx="400" cy="380" r="15" fill="var(--forest)"/>{p.courses.map((c,i)=><g key={c.id} role="button" tabIndex="0" aria-label={'Show '+c.name} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(c.id);}}}><circle cx={c.x} cy={c.y} r={selected===c.id?24:20} fill={selected===c.id?'var(--forest)':'var(--navy)'}/><text x={c.x} y={c.y+6} textAnchor="middle" fill="white">{i+1}</text><text x={c.x} y={c.y-34} textAnchor="middle">{c.name}</text></g>)}</svg></div><h4>{course.name}</h4><p>{course.drive}</p>{course.directionsUrl&&<a href={course.directionsUrl} target="_blank" rel="noopener noreferrer">Open configured directions ↗</a>}</section>;
}
function NumberField({label,value,min=0,max=10000000,step='0.01',onChange}){return <label className="field">{label}<input type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(e.target.value===''?'':Number(e.target.value))}/></label>;}
function Scope({p}){return <div className="proposal-inset"><h3>What this number covers</h3>{p.kind==='group-package'?<p>Golf, the chosen house, contest pools, mementos and group food only. Personal travel, local vehicles, personal spending and contingency are outside this budget. Compare it with another group-only total.</p>:p.kind==='shared'?<p>The shared base, personal allowance, chosen arrival route and optional practice. This model does not split out a separate hard-cost subtotal.</p>:p.kind==='split-house'?<p>Golf, two lodging shares, carts, forecaddie, vehicles and contingency make the hard base, rounded to the nearest whole dollar. Arrival and practice are then added. Personal spending makes the projected total.</p>:<p>The projected total includes the shared trip, personal spending, chosen arrival route and optional practice. The hard-cost subtotal uses the configured committed-cost base plus arrival and practice.</p>}{!['split-house','group-package'].includes(p.kind)&&<p>Shared allowances assume {p.groupSize} people. If the group changes, update the underlying quotes before treating the result as a budget.</p>}</div>;}
function CostTable({result}){return <table className="plain-table"><caption>What goes into this total</caption><tbody>{result.lines.map((r,i)=><tr key={i}><th scope="row">{r.label}</th><td>{money(r.amount)}</td></tr>)}</tbody><tfoot><tr><th>Total per person</th><td>{money(result.projected)}</td></tr></tfoot></table>;}
function Budget({p,choices,onChange,result,error}){
 const c=p.costs,change=(key,value)=>onChange({...choices,[key]:value}),origin=p.origins.find(o=>o.id===choices.origin);
 return <div className="proposal-budget-grid"><section className="card"><h2>Make the numbers yours</h2><p>These are planning allowances per person. Change the scenario, then check the scope before comparing totals.</p>
 {p.kind!=='group-package'&&<><label className="field">Your arrival route<select value={choices.origin} onChange={e=>change('origin',e.target.value)}>{p.origins.map(o=><option value={o.id} key={o.id}>{o.name} ({money(o.cost)})</option>)}</select></label>{origin&&<div className="proposal-inset"><strong>{origin.route}</strong><p>{origin.arrival}. {origin.transfer}</p></div>}<label className="check-row"><input type="checkbox" checked={choices.practice===true} onChange={e=>change('practice',e.target.checked)}/>Add the practice round ({money(p.practiceCost)})</label></>}
 {p.kind==='winner'&&<label className="check-row"><input type="checkbox" checked={choices.winner===true} onChange={e=>change('winner',e.target.checked)}/>Show the hypothetical winner return ({money(c.winnerReturn)})</label>}
 {'groupSize' in choices&&<NumberField label="People splitting the lodging" value={choices.groupSize} min={1} max={80} step="1" onChange={v=>change('groupSize',v)}/>}
 {p.kind==='group-package'&&<><label className="field">Shared house<select value={choices.house} onChange={e=>change('house',e.target.value)}>{c.houses.map(h=><option key={h.id} value={h.id} disabled={h.total===null}>{h.name} ({h.total===null?'awaiting quote':money(h.total)+' for the stay'})</option>)}</select></label><label className="field">Finale package<select value={choices.package} onChange={e=>change('package',e.target.value)}>{c.packages.map(k=><option key={k.id} value={k.id}>{k.name} ({money(k.amount)})</option>)}</select></label><NumberField label={`Premium round rate (${money(c.premiumMin)} to ${money(c.premiumMax)})`} value={choices.premiumRate} min={c.premiumMin} max={c.premiumMax} onChange={v=>change('premiumRate',v)}/><label className="check-row"><input type="checkbox" checked={choices.replay===true} onChange={e=>change('replay',e.target.checked)}/>Add a replay at the same premium rate</label><p className="inline-note">The package rounds, one premium round and any replay are counted separately. A replay assumes the same rate; replace that assumption if you get a different quote.</p></>}
 <NumberField label="Per-person target" value={choices.target} onChange={v=>change('target',v)}/><button className="btn btn2" onClick={()=>onChange(defaultChoices(p))}>Reset this scenario</button>{error&&<p className="error-note" role="alert">{error}</p>}</section>
 <section className="card proposal-totals" aria-live="polite"><div className="cl">{p.kind==='group-package'?'Group budget per person':p.kind==='winner'&&choices.winner?'Projected net per person':'Projected per person'}</div><p className="proposal-price" data-testid="proposal-total">{result?money(result.projected):'Check the inputs'}</p>{result&&<><p>{result.rounds} rounds · {result.groupSize} people in this example</p>{result.hard!==null&&<div className="proposal-secondary"><span>Hard-cost subtotal</span><strong data-testid="proposal-hard">{money(result.hard)}</strong></div>}{result.credit>0&&<p className="inline-note">Before any hypothetical return: {money(result.beforeCredit)}. The credit changes your scenario, not what the group has to collect.</p>}<div className={'proposal-target '+(result.headroom<0?'over':'')} data-testid="proposal-target">{money(Math.abs(result.headroom))} {result.headroom<0?'over':'under'} your {money(choices.target)} target</div>{result.comparison!==null&&<p>Alternate itinerary: {money(result.comparison)} per person, using the same arrival and practice allowances. This option is {money(Math.abs(result.savings))} {result.savings<0?'more':'less'}.</p>}<CostTable result={result}/></>}<Scope p={p}/></section></div>;
}
function ProposalDetail({p,back}){
 const [choices,setChoices]=useState(()=>readChoices(p)),[section,setSection]=useState('overview'),[day,setDay]=useState(p.days[0].id),[course,setCourse]=useState(p.courses[0].id),[copied,setCopied]=useState('');
 let result=null,error='',itinerary=p.days;try{result=calculateProposal(p,choices);itinerary=proposalItinerary(p,choices);}catch(e){error=e.issues?.[0]?`${e.issues[0].path.join(' ')}: ${e.issues[0].message}`:e.message;}
 const update=next=>{setChoices(next);try{calculateProposal(p,next);writeChoices(p,next);}catch{/* An invalid input stays visible, never becomes zero or a shareable result. */}};
 useEffect(()=>{const pop=()=>setChoices(readChoices(p));window.addEventListener('popstate',pop);document.body.classList.add('printing-proposal');return()=>{window.removeEventListener('popstate',pop);document.body.classList.remove('printing-proposal');};},[p]);
 const chosenDay=itinerary.find(d=>d.id===day)||itinerary[0],chosenCourse=p.courses.find(c=>c.id===course)||p.courses[0];
 async function copy(){if(!result)return;writeChoices(p,choices);try{await navigator.clipboard.writeText(location.href);setCopied('Link copied with your scenario.');}catch{setCopied(location.href);}}
 return <article className={'proposal-detail proposal-kind-'+p.kind}><div className="proposal-toolbar"><button className="btn btn2" onClick={back}>← All five ideas</button><button className="btn btn2" onClick={copy} disabled={!result}>Copy this scenario</button><button className="btn btn2" onClick={()=>window.print()} disabled={!result}>Print proposal</button></div>{copied&&<p className="proposal-copy" role="status">{copied}</p>}<header className="proposal-hero"><div><p className="cl">{styles[p.kind]}</p><h1>{p.name}</h1><p className="proposal-tagline">{p.tagline}</p><p>{p.description}</p><div className="proposal-hero-price">{result?money(result.projected):'Enter a valid scenario'}<span>{p.kind==='group-package'?'group budget per person':'projected per person'}</span></div></div><img src="/assets/invented-course.png" alt="Original illustration of an invented golf landscape"/></header>
 <nav className="proposal-sections" aria-label="Proposal sections">{[['overview','The idea'],['budget','Budget'],['itinerary','Day by day'],['courses','The courses'],['stay','Stay & getting around']].map(([id,label])=><button key={id} className={'btn '+(section===id?'btn1':'btn2')} aria-pressed={section===id} onClick={()=>setSection(id)}>{label}</button>)}</nav>
 <div className="proposal-screen-content">{section==='overview'&&<><section className="card"><h2>A plan people can react to</h2><p>Start with the shape of the trip, compare the costs, then use the group poll to find common ground. The illustrations, places and prices here are invented examples.</p><div className="proposal-highlights"><div><strong>{p.days.length} days</strong><span>A complete outline</span></div><div><strong>{result?.rounds??'—'} rounds</strong><span>With your current choices</span></div><div><strong>{styles[p.kind]}</strong><span>A distinct budget model</span></div></div><button className="btn btn1" onClick={()=>setSection('budget')}>Try the budget</button> <a className="btn btn2" href="#poll">Answer the trip poll</a></section><Gallery images={p.gallery}/><section className="card"><h2>Before making it real</h2><ul>{p.logistics.map(t=><li key={t}>{t}</li>)}</ul><p>Use images and course descriptions you own or have permission to share. Keep guest details and private booking information in your private event.</p></section></>}
 {section==='budget'&&<Budget p={p} choices={choices} onChange={update} result={result} error={error}/>}
 {section==='itinerary'&&<section className="card"><h2>A little structure, some room to breathe</h2><div className="proposal-picker">{itinerary.map(d=><button key={d.id} className={'btn '+(day===d.id?'btn1':'btn2')} aria-pressed={day===d.id} onClick={()=>setDay(d.id)}>{d.label}</button>)}</div><h3>{chosenDay.title}</h3>{error&&<p role="alert">Correct the budget inputs to see the selected round schedule.</p>}<ol className="proposal-timeline">{[...(chosenDay.roundLabels||[]),...chosenDay.items].map((t,i)=><li key={i}>{t}</li>)}</ol><p className="inline-note">This is an outline, not a reservation. Match tee times, transport and arrival deadlines to confirmed bookings.</p></section>}
 {section==='courses'&&<section className="card"><h2>Different days, different tests</h2><div className="proposal-picker">{p.courses.map(c=><button key={c.id} className={'btn '+(course===c.id?'btn1':'btn2')} aria-pressed={course===c.id} onClick={()=>setCourse(c.id)}>{c.name}</button>)}</div><img className="proposal-course-image" src={chosenCourse.image} alt={'Illustrated example for '+chosenCourse.name}/><h3>{chosenCourse.name}</h3><p>{chosenCourse.description}</p><div className="proposal-highlights"><div><strong>{money(chosenCourse.fee)}</strong><span>Illustrative course allowance</span></div><div><strong>{chosenCourse.walkable?'Walking option':'Plan for a cart'}</strong><span>Example transport plan</span></div><div><strong>{chosenCourse.drive}</strong><span>Invented transfer time</span></div></div><details><summary>Rate notes & booking checks</summary><ul>{chosenCourse.notes.map(n=><li key={n}>{n}</li>)}</ul><p>{p.kind==='group-package'?'These course cards are illustrative. The package and editable premium rate determine the calculator total.':'Reconfirm the total rate, inclusions and availability for your actual dates.'}</p></details>{chosenCourse.directionsUrl&&<a href={chosenCourse.directionsUrl} target="_blank" rel="noopener noreferrer">Course directions ↗</a>}{p.kind==='split-house'&&<div className="table-scroll"><table className="plain-table"><caption>Compare the rate conditions</caption><thead><tr><th>Rate type</th><th>Allowance</th><th>Assumption</th></tr></thead><tbody>{p.costs.rateContext.map(r=><tr key={r.label}><td>{r.label}</td><td>{money(r.amount)}</td><td>{r.note}</td></tr>)}</tbody></table></div>}</section>}
 {section==='stay'&&<><section className="card"><h2>A base that works for the group</h2>{p.costs.houses?p.costs.houses.map(h=><div key={h.id} className="proposal-house"><h3>{h.name}</h3><p>{h.total===null?'Awaiting a complete quote. This option cannot be selected.':money(h.total)+' for the full stay, shared across the selected group.'}</p>{h.description&&<p>{h.description}</p>}{h.directionsUrl&&<a href={h.directionsUrl} target="_blank" rel="noopener noreferrer">House directions ↗</a>}</div>):<p>The lodging allowance is included in the shared base. Confirm bed arrangements, accessibility, cancellation terms and the total stay cost before choosing a real place.</p>}<Gallery images={p.gallery}/></section><RouteMap p={p}/><section className="card"><h2>Arrival options</h2>{p.kind==='group-package'&&<p>Personal travel is outside this proposal’s group budget.</p>}{p.origins.map(o=><details key={o.id}><summary>{o.name}: {money(o.cost)} illustrative allowance</summary><p>{o.route}</p><p>{o.arrival}. {o.transfer}</p></details>)}</section></>}
 </div><section className="proposal-print-only"><h2>Current scenario</h2>{result&&<><p>{money(result.projected)} per person · {result.rounds} rounds · {result.travelIncluded?'Chosen travel allowance included':'Personal travel excluded'}</p><CostTable result={result}/><Scope p={p}/></>}<h2>Itinerary</h2>{itinerary.map(d=><div key={d.id}><h3>{d.label}: {d.title}</h3><ul>{[...(d.roundLabels||[]),...d.items].map((t,i)=><li key={i}>{t}</li>)}</ul></div>)}<h2>Planning notes</h2><ul>{p.logistics.map(t=><li key={t}>{t}</li>)}</ul><p>Invented example. Confirm actual quotes and bookings before using this plan.</p></section></article>;
}
export default function ProposalsTab(){
 const [selected,setSelected]=useState(locationChoice);
 useEffect(()=>{const changed=()=>setSelected(locationChoice());window.addEventListener('popstate',changed);return()=>window.removeEventListener('popstate',changed);},[]);
 const p=catalog.proposals.find(p=>p.id===selected);
 const choose=id=>{const url=new URL(location.href);for(const key of [...url.searchParams.keys()])if(key.startsWith('p_')||key==='proposal')url.searchParams.delete(key);if(id)url.searchParams.set('proposal',id);url.hash='proposals';history.pushState(null,'',url);setSelected(id);window.scrollTo({top:0});};
 if(p)return <ProposalDetail key={p.id} p={p} back={()=>choose('')}/>;
 return <section className="proposal-hub"><p className="cl">The next good weekend starts here</p><h1 className="st">Five ways to make a golf trip happen.</h1><p className="ss">A compact weekend, a resort-style retreat, a road trip, two cottages or a flexible group package. Each has its own useful budget model.</p>{selected&&<p className="error-note" role="alert">That proposal does not exist. Choose one below.</p>}<p className="card">All places, prices and pictures in these examples are invented. Open an idea to explore its itinerary, courses, travel choices and calculator. Totals with different scopes should not be compared as though they cover the same things.</p><div className="proposal-cards">{catalog.proposals.map((p,i)=>{const r=calculateProposal(p);return <article className="proposal-card" key={p.id}><img src={i===3?'/assets/invented-cottage.png':'/assets/invented-course.png'} alt="Original illustration for an invented trip idea" loading="lazy"/><div><span className="cl">Idea {i+1} · {styles[p.kind]}</span><h2>{p.name}</h2><p>{p.tagline}</p><strong>{money(r.projected)} <small>{p.kind==='group-package'?'group budget per person':'projected per person'}</small></strong><p>{r.rounds} rounds with the default choices. {r.travelIncluded?'Includes the nearby-driver allowance.':'Personal travel excluded.'}</p><button className="btn btn1" onClick={()=>choose(p.id)}>Explore {p.name}</button></div></article>;})}</div><p className="inline-note">Your calculator choices stay in this page’s link. They do not change the group’s tournament or poll answers.</p></section>;
}
